//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alunos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alunos()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int Id_Aluno { get; set; }
        public string Nome { get; set; }
        public string Sexo { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<bool> Excluido { get; set; }
        public Nullable<int> Id_Materia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
