//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itens_Nota
    {
        public int Id_ItensNota { get; set; }
        public Nullable<int> Id_Produto { get; set; }
        public string Nome { get; set; }
        public Nullable<int> ValorUnitario { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<int> ValorTotar { get; set; }
        public Nullable<int> Id_Nota { get; set; }
    
        public virtual Nota Nota { get; set; }
    }
}
