//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula_MVC_Top.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int Id_produtto { get; set; }
        public string Descricao { get; set; }
        public int Quantidade { get; set; }
        public string Preco_Venda { get; set; }
    }
}
