//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula_MVC_Top.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public int Id_professor { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Idade { get; set; }
        public string Cpf { get; set; }
        public string Senha { get; set; }
    }
}
